### ISSUE TITLE
.cache/torch_extensions/py38_cu117/utils/utils.so

### ISSUE THREAD

**Issue by zhujiagang** [Sierkinhane/VisorGPT#1]
Thanks for sharing your excellent work!

When I run the training command, I met the following error.

> Loading extension module utils...
> Traceback (most recent call last):
>   File "pretrain.py", line 121, in <module>
>     main()
>   File "pretrain.py", line 117, in main
>     trainer.train_and_validate(args)
>   File "/mnt/data-1/data/jiagang.zhu/VisorGPT/train/tencentpretrain/trainer.py", line 56, in train_and_validate
>     worker(args.local_rank, None, args, model_for_training, model_for_dataloader)
>   File "/mnt/data-1/data/jiagang.zhu/VisorGPT/train/tencentpretrain/trainer.py", line 593, in worker
>     model_for_training, optimizer, _, scheduler = deepspeed.initialize(
>   File "/mnt/data-1/data/jiagang.zhu/miniconda3/envs/visorgpt/lib/python3.8/site-packages/deepspeed/__init__.py", line 125, in initialize
>     engine = DeepSpeedEngine(args=args,
>   File "/mnt/data-1/data/jiagang.zhu/miniconda3/envs/visorgpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 336, in __init__
>     self._configure_optimizer(optimizer, model_parameters)
>   File "/mnt/data-1/data/jiagang.zhu/miniconda3/envs/visorgpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1284, in _configure_optimizer
>     self.optimizer = self._configure_zero_optimizer(basic_optimizer)
>   File "/mnt/data-1/data/jiagang.zhu/miniconda3/envs/visorgpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1533, in _configure_zero_optimizer
>     optimizer = DeepSpeedZeroOptimizer(
>   File "/mnt/data-1/data/jiagang.zhu/miniconda3/envs/visorgpt/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 165, in __init__
>     util_ops = UtilsBuilder().load()
>   File "/mnt/data-1/data/jiagang.zhu/miniconda3/envs/visorgpt/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 485, in load
>     return self.jit_load(verbose)
>   File "/mnt/data-1/data/jiagang.zhu/miniconda3/envs/visorgpt/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 520, in jit_load
>     op_module = load(
>   File "/mnt/data-1/data/jiagang.zhu/miniconda3/envs/visorgpt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
>     return _jit_compile(
>   File "/mnt/data-1/data/jiagang.zhu/miniconda3/envs/visorgpt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1534, in _jit_compile
>     return _import_module_from_library(name, build_directory, is_python_module)
>   File "/mnt/data-1/data/jiagang.zhu/miniconda3/envs/visorgpt/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1936, in _import_module_from_library
>     module = importlib.util.module_from_spec(spec)
>   File "<frozen importlib._bootstrap>", line 556, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 1166, in create_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> ImportError: /home/user001/.cache/torch_extensions/py38_cu117/utils/utils.so: cannot open shared object file: No such file or directory

Have you met this problem before? Thank you.

**Comment by Sierkinhane** [comment]
Hi, I will check the problem soon. It seems to be the incompatible problem of torch and deepspeed. Maybe you can try to train the model using the environment below:
```
torch=1.7.1
deepspeed==0.7
```

**Comment by zhujiagang** [comment]
When I run `pip3 install -r requirements.txt`, I met the following error

> ERROR: Could not install packages due to an OSError: [Errno 2] 没有那个文件或目录: '/opt/conda/conda-bld/flit-core_1644941570762/work/source/flit_core'
https://github.com/Sierkinhane/VisorGPT/blob/6f1252f9859f62707fe31faf4913b9e4efad05b3/requirements.txt#L36

It seems that the requirements.txt needs rearrangements.

**Comment by zhujiagang** [comment]
We don't have A100. We use 3090 for training and inference. We can run the gradio inference but fail to run training.

**Comment by zhujiagang** [comment]
This problem has been solved by compiling deepspeed from source instead of using `pip install deepspeed`
https://github.com/microsoft/DeepSpeed/issues/2187.

- Uninstall DeepSpeed  `pip uninstall deepspeed`
- clone  repo  `git clone https://github.com/microsoft/DeepSpeed.git && cd DeepSpeed`
- install `DS_BUILD_UTILS=1 pip install .`

Thanks a lot.

**Comment by Sierkinhane** [comment]
Great!
